### ISSUE TITLE
LDAP check for is_resource breaks

### ISSUE THREAD

**Issue by marshmanGit** [popphp/pop-auth#1]
It appears that as of PHP 8.0, the LDAP no longer returns a "resource" but instead returns an object of LDAP\Connection class.
The addition to check "is_resource()" fails and breaks any LDAP ability to connect.  Recommend change to is_object()
thx
marshall

    /**
     * Method to authenticate
     *
     * @param  string $username
     * @param  string $password
     * @return int
     */
    public function authenticate($username, $password)
    {
        $this->setUsername($username);
        $this->setPassword($password);

        if (is_resource($this->resource)) {
            $this->result = (int)(@ldap_bind($this->resource, $this->username, $this->password));
        }

        return $this->result;
    }

**Comment by nicksagona** [comment]
Ok, thanks for bringing this up. Check out v3.3.2 - it should fix the issue.
